export const projects = [
	{
		title: "Company Marketing Website",
		description: "Responsive marketing website built with Next.js and Tailwind CSS.",
		status: "done",
		priority: "medium",
	},
	{
		title: "E-commerce Platform",
		description: "Full-featured e-commerce platform with payments, carts, and admin dashboard.",
		status: "in_progress",
		priority: "high",
	},
	{
		title: "Mobile Banking App",
		description: "Secure mobile app for managing bank accounts and transactions.",
		status: "in_review",
		priority: "urgent",
	},
	{
		title: "Internal HR Dashboard",
		description: "Dashboard for managing employees, leaves, and performance reviews.",
		status: "todo",
		priority: "medium",
	},
	{
		title: "Customer Support Ticket System",
		description: "Web app for tracking and resolving customer support tickets.",
		status: "in_progress",
		priority: "high",
	},
	{
		title: "SaaS Landing Page",
		description: "High-conversion landing page for a SaaS product.",
		status: "done",
		priority: "low",
	},
	{
		title: "Project Management Tool",
		description: "Tool for managing projects, tasks, and team collaboration.",
		status: "in_progress",
		priority: "high",
	},
	{
		title: "Real Estate Listing Website",
		description: "Platform to list, search, and manage real estate properties.",
		status: "in_review",
		priority: "medium",
	},
	{
		title: "Company Blog Platform",
		description: "CMS-powered blog for publishing articles and announcements.",
		status: "done",
		priority: "low",
	},
	{
		title: "Inventory Management System",
		description: "System for tracking stock, suppliers, and warehouse movements.",
		status: "todo",
		priority: "high",
	},
	{
		title: "Fitness Tracking Mobile App",
		description: "Mobile app for tracking workouts, nutrition, and progress.",
		status: "in_progress",
		priority: "medium",
	},
	{
		title: "Online Learning Platform",
		description: "E-learning platform with courses, quizzes, and certifications.",
		status: "in_review",
		priority: "high",
	},
	{
		title: "Company Analytics Dashboard",
		description: "Dashboard visualizing KPIs and business metrics.",
		status: "done",
		priority: "medium",
	},
	{
		title: "Appointment Booking System",
		description: "Web app for booking and managing appointments online.",
		status: "in_progress",
		priority: "high",
	},
	{
		title: "Healthcare Patient Portal",
		description: "Secure portal for patients to view records and appointments.",
		status: "todo",
		priority: "urgent",
	},
	{
		title: "Restaurant Ordering App",
		description: "Online ordering system for restaurants with delivery support.",
		status: "in_review",
		priority: "medium",
	},
	{
		title: "Cloud File Storage App",
		description: "Application for uploading, storing, and sharing files securely.",
		status: "in_progress",
		priority: "high",
	},
	{
		title: "Startup Pitch Website",
		description: "Website showcasing startup vision, product, and team.",
		status: "done",
		priority: "low",
	},
	{
		title: "CRM System",
		description: "Customer relationship management system for sales teams.",
		status: "todo",
		priority: "high",
	},
	{
		title: "AI Chatbot Integration",
		description: "Integrating AI chatbot for customer support automation.",
		status: "in_review",
		priority: "urgent",
	},
	{
		title: "Event Management Platform",
		description: "Platform for creating and managing events and registrations.",
		status: "in_progress",
		priority: "medium",
	},
	{
		title: "Corporate Intranet Portal",
		description: "Internal portal for company news and resources.",
		status: "done",
		priority: "low",
	},
	{
		title: "Logistics Tracking System",
		description: "System for tracking shipments and delivery statuses.",
		status: "todo",
		priority: "high",
	},
	{
		title: "Job Board Website",
		description: "Platform for posting and applying for jobs.",
		status: "in_progress",
		priority: "medium",
	},
	{
		title: "Online Payment Gateway Integration",
		description: "Integrating secure online payment solutions.",
		status: "in_review",
		priority: "urgent",
	},
	{
		title: "Travel Booking Website",
		description: "Website for booking flights, hotels, and tours.",
		status: "done",
		priority: "medium",
	},
	{
		title: "IoT Device Management Dashboard",
		description: "Dashboard for monitoring and managing IoT devices.",
		status: "todo",
		priority: "high",
	},
	{
		title: "Social Media Management Tool",
		description: "Tool for scheduling and analyzing social media posts.",
		status: "in_progress",
		priority: "medium",
	},
	{
		title: "Cybersecurity Monitoring App",
		description: "Application for monitoring security threats and alerts.",
		status: "in_review",
		priority: "urgent",
	},
	{
		title: "Digital Wallet App",
		description: "Mobile wallet app for payments and transfers.",
		status: "todo",
		priority: "high",
	},
	{
		title: "Company Knowledge Base",
		description: "Internal knowledge base for documentation and guides.",
		status: "done",
		priority: "low",
	},
	{
		title: "Video Streaming Platform",
		description: "Platform for uploading and streaming video content.",
		status: "in_progress",
		priority: "high",
	},
	{
		title: "Fleet Management System",
		description: "System to manage vehicles, drivers, and routes.",
		status: "todo",
		priority: "medium",
	},
	{
		title: "Online Survey Tool",
		description: "Tool for creating and analyzing surveys.",
		status: "done",
		priority: "low",
	},
	{
		title: "E-signature Platform",
		description: "Platform for signing and managing digital documents.",
		status: "in_review",
		priority: "high",
	},
	{
		title: "Retail POS System",
		description: "Point-of-sale system for retail stores.",
		status: "in_progress",
		priority: "medium",
	},
	{
		title: "Smart Home Control App",
		description: "Mobile app to control and monitor smart home devices.",
		status: "todo",
		priority: "high",
	},
	{
		title: "Company Feedback Tool",
		description: "Internal tool for collecting employee feedback.",
		status: "done",
		priority: "low",
	},
	{
		title: "AI Recommendation Engine",
		description: "Engine for generating personalized product recommendations.",
		status: "in_progress",
		priority: "urgent",
	},
	{
		title: "Marketplace Platform",
		description: "Multi-vendor marketplace for buying and selling products.",
		status: "in_review",
		priority: "high",
	},
	{
		title: "Chat Application",
		description: "Real-time chat application with group messaging.",
		status: "done",
		priority: "medium",
	},
	{
		title: "Subscription Billing System",
		description: "System for managing subscriptions and recurring payments.",
		status: "in_progress",
		priority: "high",
	},
	{
		title: "Code Review Platform",
		description: "Platform for managing and reviewing code changes.",
		status: "todo",
		priority: "medium",
	},
	{
		title: "Online Form Builder",
		description: "Tool for building and embedding custom forms.",
		status: "done",
		priority: "low",
	},
	{
		title: "Monitoring & Alerting System",
		description: "System for monitoring services and sending alerts.",
		status: "in_review",
		priority: "urgent",
	},
	{
		title: "Company Email Automation Tool",
		description: "Tool for automating transactional and marketing emails.",
		status: "in_progress",
		priority: "medium",
	},
	{
		title: "DevOps CI/CD Pipeline",
		description: "Automated CI/CD pipeline for deploying applications.",
		status: "done",
		priority: "high",
	},
	{
		title: "AI-powered Search Feature",
		description: "Semantic search feature using AI embeddings.",
		status: "todo",
		priority: "urgent",
	},
];
