import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { SparklesIcon } from "@/components/ui/sparkles-icon";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";
import { Info } from "lucide-react";

type actions = Array<string>;

export default function AiActions({ actions }: { actions: actions }) {
	return (
		<Card className="gap-2 pb-1">
			<CardHeader>
				<CardTitle className="flex items-center gap-1">
					<div className="bg-muted p-2 rounded-md grid place-content-center">
						<SparklesIcon size={14} />
					</div>
					AI Recommended Actions
					<Tooltip>
						<TooltipTrigger>
							<Info size="12" />
						</TooltipTrigger>
						<TooltipContent className="bg-muted/90 text-muted-foreground text-xs">
							<p>
								These actions are generated by AI based on the current state of your
								projects and team workload.
							</p>
						</TooltipContent>
					</Tooltip>
				</CardTitle>
			</CardHeader>
			<CardContent className="gap-0">
				<ul className="list-disc pl-4 space-y-2 mb-4">
					{actions.map((action: string, index: number) => (
						<li key={`ai-action-${index}`} className="first-letter:uppercase">
							{action}
						</li>
					))}
				</ul>
			</CardContent>
		</Card>
	);
}
